before:
  hooks:
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    binary: bngblasterctrl
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  -
    maintainer: RtBrick <bngblaster@rtbrick.com>
    license: "BSD-3"
    formats:
      - deb
    files:
      "debian/scripts/systemd/rtbrick-bngblasterctrl.service": "/etc/systemd/system/rtbrick-bngblasterctrl.service"
    scripts:
      postinstall: debian/scripts/postinstall.sh
      preremove: debian/scripts/preremove.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
