// SPDX-License-Identifier: BSD-3-Clause
// Copyright (C) 2020-2025, RtBrick, Inc.
package server

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gorilla/mux"

	"github.com/rtbrick/bngblaster-controller/pkg/controller"
)

const (
	defaultSessionPageSize = 50
	maxSessionPageSize     = 500
)

// sessionFilters mirrors the filter arguments accepted by the bngblaster
// "session-summary" control socket command.
type sessionFilters struct {
	SessionID      *int
	SessionGroupID *int
	SessionIDMin   *int
	SessionIDMax   *int
}

func parseSessionFilters(r *http.Request) sessionFilters {
	f := sessionFilters{}
	f.SessionID = parseOptionalIntQuery(r, "session-id")
	f.SessionGroupID = parseOptionalIntQuery(r, "session-group-id")
	f.SessionIDMin = parseOptionalIntQuery(r, "session-id-min")
	f.SessionIDMax = parseOptionalIntQuery(r, "session-id-max")
	return f
}

// cacheKey is a stable string encoding of the filter set, used as (part of)
// the session-summary cache key.
func (f sessionFilters) cacheKey() string {
	key := ""
	if f.SessionID != nil {
		key += fmt.Sprintf("|session-id=%d", *f.SessionID)
	}
	if f.SessionGroupID != nil {
		key += fmt.Sprintf("|session-group-id=%d", *f.SessionGroupID)
	}
	if f.SessionIDMin != nil {
		key += fmt.Sprintf("|session-id-min=%d", *f.SessionIDMin)
	}
	if f.SessionIDMax != nil {
		key += fmt.Sprintf("|session-id-max=%d", *f.SessionIDMax)
	}
	return key
}

// arguments builds the "arguments" object sent alongside the
// "session-summary" socket command.
func (f sessionFilters) arguments() map[string]interface{} {
	args := map[string]interface{}{}
	if f.SessionID != nil {
		args["session-id"] = *f.SessionID
	}
	if f.SessionGroupID != nil {
		args["session-group-id"] = *f.SessionGroupID
	}
	if f.SessionIDMin != nil {
		args["session-id-min"] = *f.SessionIDMin
	}
	if f.SessionIDMax != nil {
		args["session-id-max"] = *f.SessionIDMax
	}
	return args
}

// sessionsResponse is the paginated view of session-summary returned to the
// UI, mirroring streamsResponse's "floating range" contract for the
// virtual-scrolling session table.
type sessionsResponse struct {
	Total  int                                `json:"total"`
	Offset int                                `json:"offset"`
	Limit  int                                `json:"limit"`
	Items  []controller.SessionSummarySession `json:"items"`
}

// sessions implements the "floating range" pagination endpoint backing the
// virtual-scrolling session table: GET .../_sessions?offset=&limit=
func (s *Server) sessions() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		instanceVariable := mux.Vars(r)[instanceNameParameter]
		instance := cleanPathVariable(instanceVariable)
		if !s.repository.Exists(instance) {
			JSONNotFound(w, r)
			return
		}

		offset := parseNonNegativeIntQuery(r, "offset", 0)
		limit := parseNonNegativeIntQuery(r, "limit", defaultSessionPageSize)
		if limit <= 0 {
			limit = defaultSessionPageSize
		}
		if limit > maxSessionPageSize {
			limit = maxSessionPageSize
		}

		filters := parseSessionFilters(r)
		// See streams(): "window=1" distinguishes a range the virtual scroller
		// derived from its scroll position from one the user typed in.
		windowed := r.URL.Query().Get("window") == "1" && filters.SessionIDMin != nil && filters.SessionIDMax != nil
		cacheKey := instance + filters.cacheKey()

		sessionsData, err := s.sessionCache.get(cacheKey, func() ([]controller.SessionSummarySession, error) {
			result, err := s.repository.Command(instance, controller.SocketCommand{
				Command:   "session-summary",
				Arguments: filters.arguments(),
			})
			if err != nil {
				return nil, err
			}
			var parsed controller.SessionSummaryResponse
			if err := json.Unmarshal(result, &parsed); err != nil {
				return nil, err
			}
			return parsed.Sessions, nil
		})
		if err == controller.ErrBlasterNotRunning {
			JSONError(w, "instance is not running", http.StatusPreconditionFailed)
			return
		}
		if err != nil {
			JSONError(w, "not able to fetch session summary", http.StatusInternalServerError)
			return
		}

		var resp sessionsResponse
		if windowed {
			// Same reasoning as streams(): a session-id range generated by the
			// UI's virtual-scroll window is already exactly the slice about to
			// be rendered, and Offset is the absolute row index it starts at.
			resp = sessionsResponse{
				Total:  len(sessionsData),
				Offset: *filters.SessionIDMin - 1,
				Limit:  limit,
				Items:  sessionsData,
			}
		} else {
			// Everything else - including a user-entered session-id range - is
			// plain offset/limit pagination over the filtered result.
			total := len(sessionsData)
			start := offset
			if start > total {
				start = total
			}
			end := start + limit
			if end > total {
				end = total
			}
			resp = sessionsResponse{
				Total:  total,
				Offset: start,
				Limit:  limit,
				Items:  sessionsData[start:end],
			}
		}

		w.Header().Set(contentType, applicationJSON)
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(resp)
	}
}
