// SPDX-License-Identifier: BSD-3-Clause
// Copyright (C) 2020-2026, RtBrick, Inc.
package server

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/gorilla/mux"

	"github.com/rtbrick/bngblaster-controller/pkg/controller"
)

// summaryPage is the paginated view of a summary socket command (stream- or
// session-summary) returned to the UI. This is the "floating range" contract
// used by the virtual scrolling tables: the client only ever asks for the
// slice of rows currently in (or near) the viewport instead of downloading
// the entire list.
type summaryPage[T any] struct {
	Total  int `json:"total"`
	Offset int `json:"offset"`
	Limit  int `json:"limit"`
	Items  []T `json:"items"`
}

// summaryEndpoint describes one "floating range" pagination endpoint; the
// stream and session tables differ only in these parameters.
type summaryEndpoint[T any] struct {
	command      string
	errorMessage string
	defaultLimit int
	maxLimit     int
	cache        *summaryCache[[]T]
	// query extracts the filter set from the request: the socket command
	// arguments, the cache key suffix encoding them, and - for a range the
	// UI's virtual scroller derived from its scroll position - the first id
	// of that window (nil otherwise).
	query func(r *http.Request) (args map[string]any, cacheKey string, windowStart *int)
	// items unpacks the list from the decoded socket response.
	items func(payload []byte) ([]T, error)
}

// serveSummaryPage implements a summaryEndpoint as a handler. It is a free
// function rather than a Server method because methods cannot take type
// parameters.
func serveSummaryPage[T any](s *Server, e summaryEndpoint[T]) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		instanceVariable := mux.Vars(r)[instanceNameParameter]
		instance := cleanPathVariable(instanceVariable)
		if !s.repository.Exists(instance) {
			JSONNotFound(w, r)
			return
		}

		offset := parseNonNegativeIntQuery(r, "offset", 0)
		limit := parseNonNegativeIntQuery(r, "limit", e.defaultLimit)
		if limit <= 0 {
			limit = e.defaultLimit
		}
		limit = min(limit, e.maxLimit)

		args, cacheKey, windowStart := e.query(r)
		items, err := e.cache.get(instance+cacheKey, func() ([]T, error) {
			result, err := s.repository.Command(instance, controller.SocketCommand{
				Command:   e.command,
				Arguments: args,
			})
			if err != nil {
				return nil, err
			}
			return e.items(result)
		})
		if err == controller.ErrBlasterNotRunning {
			JSONError(w, "instance is not running", http.StatusPreconditionFailed)
			return
		}
		if err != nil {
			JSONError(w, e.errorMessage, http.StatusInternalServerError)
			return
		}

		w.Header().Set(contentType, applicationJSON)
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(paginate(items, offset, limit, windowStart))
	}
}

// paginate cuts the page to return out of the (already filtered) items.
func paginate[T any](items []T, offset, limit int, windowStart *int) summaryPage[T] {
	if windowStart != nil {
		// The id range was generated by the UI's virtual-scroll window, not
		// typed by a user: it asked bngblaster for exactly the slice of rows
		// it is about to render, so that slice is returned as-is. Offset is
		// the absolute row index the slice starts at, which for a
		// sequentially assigned id chain is the first id minus one.
		return summaryPage[T]{
			Total:  len(items),
			Offset: *windowStart - 1,
			Limit:  limit,
			Items:  items,
		}
	}
	// Everything else - including a user-entered id range - is plain
	// offset/limit pagination over the filtered result. Offset is a row index
	// into that result and Total is its full length, so the client can size a
	// scrollbar for the filtered list correctly.
	total := len(items)
	start := min(offset, total)
	end := min(start+limit, total)
	return summaryPage[T]{
		Total:  total,
		Offset: start,
		Limit:  limit,
		Items:  items[start:end],
	}
}

// windowStart returns the first id of a virtual-scroll window. "window=1"
// marks an id range the UI's virtual scroller derived from its scroll
// position rather than one the user typed into the filter panel. The two
// need different pagination semantics (see paginate), and only the client
// knows which is which.
func windowStart(r *http.Request, idMin, idMax *int) *int {
	if r.URL.Query().Get("window") == "1" && idMin != nil && idMax != nil {
		return idMin
	}
	return nil
}

// setIntArgument adds an optional integer socket command argument.
func setIntArgument(args map[string]any, name string, value *int) {
	if value != nil {
		args[name] = *value
	}
}

// setStringArgument adds an optional string socket command argument.
func setStringArgument(args map[string]any, name, value string) {
	if value != "" {
		args[name] = value
	}
}

func parseOptionalIntQuery(r *http.Request, name string) *int {
	raw := r.URL.Query().Get(name)
	if raw == "" {
		return nil
	}
	v, err := strconv.Atoi(raw)
	if err != nil {
		return nil
	}
	return &v
}

func parseNonNegativeIntQuery(r *http.Request, name string, def int) int {
	raw := r.URL.Query().Get(name)
	if raw == "" {
		return def
	}
	v, err := strconv.Atoi(raw)
	if err != nil || v < 0 {
		return def
	}
	return v
}
